package eu.kanade.presentation.theme.colorscheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/**
 * Colors for Cottoncandy theme
 * M3 colors generated by Material Theme Builder (https://goo.gle/material-theme-builder-web)
 *
 * Key colors:
 * Primary 0xFFF38020
 * Secondary 0xFFF38020
 * Tertiary 0xFF1B1B22
 * Neutral 0xFF655C5A
 */
internal object CottoncandyColorScheme : BaseColorScheme() {

    override val darkScheme = darkColorScheme(
        primary = Color(0xFFFFB1C1),
        onPrimary = Color(0xFF5F112B),
        primaryContainer = Color(0xFF7C2941),
        onPrimaryContainer = Color(0xFFFFD9DF),
        secondary = Color(0xFF64D3FF),
        onSecondary = Color(0xFF003546),
        secondaryContainer = Color(0xFF004D63),
        onSecondaryContainer = Color(0xFFBCE9FF),
        tertiary = Color(0xFFFFB1C1),
        onTertiary = Color(0xFF5F112B), // Note: onTertiary color is assumed
        tertiaryContainer = Color(0xFF7C2941),
        onTertiaryContainer = Color(0xFFFFD9DF),
        background = Color(0xFF201A1B),
        onBackground = Color(0xFFECE0E0),
        surface = Color(0xFF201A1B),
        onSurface = Color(0xFFECE0E0),
        surfaceVariant = Color(0xFF524345),
        onSurfaceVariant = Color(0xFFD6C2C4),
        surfaceTint = Color(0xFFFFB1C1),
        inverseSurface = Color(0xFFECE0E0),
        inverseOnSurface = Color(0xFF201A1B),
        outline = Color(0xFF9F8C8F),
        inversePrimary = Color(0xFF9A4058),
    )

    override val lightScheme = lightColorScheme(
        primary = Color(0xFF9A4058),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFD9DF),
        onPrimaryContainer = Color(0xFF3F0017),
        secondary = Color(0xFF5BCEFA),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFBCE9FF),
        onSecondaryContainer = Color(0xFF001F2A),
        tertiary = Color(0xFF9A4058),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFFFD9DF),
        onTertiaryContainer = Color(0xFF3F0017),
        background = Color(0xFFFFFBFF),
        onBackground = Color(0xFF201A1B),
        surface = Color(0xFFFFFBFF),
        onSurface = Color(0xFF201A1B),
        surfaceVariant = Color(0xFFF3DDE0),
        onSurfaceVariant = Color(0xFF524345),
        surfaceTint = Color(0xFF9A4058),
        inverseSurface = Color(0xFF352F30),
        inverseOnSurface = Color(0xFFFAEEEF),
        outline = Color(0xFF847375),
        inversePrimary = Color(0xFFFFB1C1),
    )
}
