package eu.kanade.presentation.theme.colorscheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/**
 * Colors for Sapphire theme
 * Original color scheme by LuftVerbot
 * M3 colors generated by Material Theme Builder (https://goo.gle/material-theme-builder-web)
 *
 * Key colors:
 * Primary 0xFFF38020
 * Secondary 0xFFF38020
 * Tertiary 0xFF6B5E2F
 * Neutral 0xFF655C5A
 */
internal object SapphireColorScheme : BaseColorScheme() {

    override val darkScheme = darkColorScheme(
        primary = Color(0xFF1E88E5),
        onPrimary = Color(0xFFFAFAFA),
        primaryContainer = Color(0xFF1E88E5),
        onPrimaryContainer = Color(0xFFFAFAFA),
        inversePrimary = Color(0xFF2979FF), // Assuming 'inversePrimary' maps to 'sapphire_primaryInverse'
        secondary = Color(0xFF1E88E5),
        onSecondary = Color(0xFFFAFAFA),
        secondaryContainer = Color(0xFF1E88E5),
        onSecondaryContainer = Color(0xFFFAFAFA),
        tertiary = Color(0xFF212121),
        onTertiary = Color(0xFF1E88E5),
        tertiaryContainer = Color(0xFF212121),
        onTertiaryContainer = Color(0xFF1E88E5),
        background = Color(0xFF212121),
        onBackground = Color(0xFFFFFFFF),
        surface = Color(0xFF212121),
        onSurface = Color(0xFFFFFFFF),
        surfaceVariant = Color(0xFF424242),
        onSurfaceVariant = Color(0xFFD8FFFFFF),
        surfaceTint = Color(0xFF1E88E5), // Assuming 'surfaceTint' maps to 'sapphire_primary' or similar
        inverseSurface = Color(0xFFFAFAFA),
        inverseOnSurface = Color(0xFF313131),
        outline = Color(0xFF1E88E5),
    )

    override val lightScheme = lightColorScheme(
        primary = Color(0xFF1E88E5),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFF1E88E5),
        onPrimaryContainer = Color(0xFFFFFFFF),
        inversePrimary = Color(0xFF2979FF), // Assuming 'inversePrimary' maps to 'sapphire_primaryInverse'
        secondary = Color(0xFF1E88E5),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFF1E88E5),
        onSecondaryContainer = Color(0xFFFFFFFF),
        tertiary = Color(0xFFE1F5FE),
        onTertiary = Color(0xFF1E88E5),
        tertiaryContainer = Color(0xFFE1F5FE),
        onTertiaryContainer = Color(0xFF1E88E5),
        background = Color(0xFFFFFFFF),
        onBackground = Color(0xFF212121),
        surface = Color(0xFFFFFFFF),
        onSurface = Color(0xFF212121),
        surfaceVariant = Color(0xFFB3E5FC),
        onSurfaceVariant = Color(0xFFD849454E),
        surfaceTint = Color(0xFF1E88E5), // Assuming 'surfaceTint' maps to 'sapphire_primary' or similar
        inverseSurface = Color(0xFF424242),
        inverseOnSurface = Color(0xFFFAFAFA),
        outline = Color(0xFF1E88E5),
    )
}
