name: Build APK

on:
  push:
    branches:
      - main
      - feature/first-change
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK (separated by branch)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-${{ github.ref_name }}
          path: app/build/outputs/apk/debug/*.apk
